// Code in this package is generated by bpf2go. abi_test.go is hand-written
// and asserts key map-shape contracts for the trace_connect BPF object.
//
// Pure spec parse via cilium/ebpf — no kernel needed.
package traceconnect

import (
	"testing"

	"github.com/cilium/ebpf"
)

func TestTraceconnectMapShapes(t *testing.T) {
	spec, err := LoadTraceconnect()
	if err != nil {
		t.Fatalf("LoadTraceconnect: %v", err)
	}

	t.Run("ringbuf maps keep 1<<24 capacity", func(t *testing.T) {
		ringbufMaps := []string{"connect_events", "udp_events", "http_events", "tls_events", "tcp_state_events"}
		for _, name := range ringbufMaps {
			ms, ok := spec.Maps[name]
			if !ok {
				t.Fatalf("map %s not found in CollectionSpec", name)
			}
			if ms.Type != ebpf.RingBuf {
				t.Errorf("%s type = %v, want ebpf.RingBuf", name, ms.Type)
			}
			if ms.MaxEntries != 1<<24 {
				t.Errorf("%s MaxEntries = %d, want %d (1<<24)", name, ms.MaxEntries, 1<<24)
			}
		}
	})

	t.Run("tcp_v4_connect_inflight is a bounded LRU_HASH (P3-2 correlation)", func(t *testing.T) {
		// LRU_HASH (not plain HASH) ensures that orphaned entries from
		// dropped kretprobes are evicted by the kernel rather than filling
		// the table and silently blocking every subsequent BPF_NOEXIST
		// insert (P3-bug-audit Bug 3).
		ms, ok := spec.Maps["tcp_v4_connect_inflight"]
		if !ok {
			t.Fatal("map tcp_v4_connect_inflight not found in CollectionSpec")
		}
		if ms.Type != ebpf.LRUHash {
			t.Errorf("tcp_v4_connect_inflight type = %v, want ebpf.LRUHash", ms.Type)
		}
		if ms.MaxEntries != 4096 {
			t.Errorf("tcp_v4_connect_inflight MaxEntries = %d, want 4096", ms.MaxEntries)
		}
		if ms.KeySize != 8 {
			t.Errorf("tcp_v4_connect_inflight KeySize = %d, want 8", ms.KeySize)
		}
		if ms.ValueSize != 1 {
			t.Errorf("tcp_v4_connect_inflight ValueSize = %d, want 1", ms.ValueSize)
		}
	})

	t.Run("connect4_by_tgid_fd stays bounded LRU hash", func(t *testing.T) {
		ms, ok := spec.Maps["connect4_by_tgid_fd"]
		if !ok {
			t.Fatal("map connect4_by_tgid_fd not found in CollectionSpec")
		}
		if ms.Type != ebpf.LRUHash {
			t.Errorf("connect4_by_tgid_fd type = %v, want ebpf.LRUHash", ms.Type)
		}
		if ms.MaxEntries != 16384 {
			t.Errorf("connect4_by_tgid_fd MaxEntries = %d, want 16384", ms.MaxEntries)
		}
		if ms.KeySize != 8 {
			t.Errorf("connect4_by_tgid_fd KeySize = %d, want 8", ms.KeySize)
		}
		// P5: connect4_tuple grew from 8 → 24 bytes
		// (daddr[4] + dport[2] + in_use + is_ipv6 + daddr6[16]) so the LRU
		// map value carries the v6 address for IPv6 TLS attribution.
		if ms.ValueSize != 24 {
			t.Errorf("connect4_by_tgid_fd ValueSize = %d, want 24", ms.ValueSize)
		}
	})

	// Singleton ARRAY maps that legitimately stay global: userspace writes
	// while BPF reads (tls_agent_cfg, canary_trigger). Per-CPU semantics
	// would not apply.
	t.Run("singleton ARRAY control maps", func(t *testing.T) {
		cases := []struct {
			mapName   string
			valueSize uint32
		}{
			{"tls_agent_cfg", 1},
			{"canary_trigger", 8},
		}
		for _, c := range cases {
			ms, ok := spec.Maps[c.mapName]
			if !ok {
				t.Errorf("map %s not found in CollectionSpec", c.mapName)
				continue
			}
			if ms.Type != ebpf.Array {
				t.Errorf("%s type = %v, want ebpf.Array", c.mapName, ms.Type)
			}
			if ms.MaxEntries != 1 {
				t.Errorf("%s MaxEntries = %d, want 1", c.mapName, ms.MaxEntries)
			}
			if ms.KeySize != 4 {
				t.Errorf("%s KeySize = %d, want 4", c.mapName, ms.KeySize)
			}
			if ms.ValueSize != c.valueSize {
				t.Errorf("%s ValueSize = %d, want %d", c.mapName, ms.ValueSize, c.valueSize)
			}
		}
	})

	t.Run("PERCPU_ARRAY reserve, tuple-failure, and observation maps", func(t *testing.T) {
		names := []string{
			"connect4_tuple_update_failures",
			"udp_ringbuf_reserve_failures",
			"connect_ringbuf_reserve_failures",
			"http_ringbuf_reserve_failures",
			"tls_ringbuf_reserve_failures",
			"sendmmsg_multi_message_observed",
			"sendmmsg_unobserved_extra",
			"udp_sendmsg_multi_iovec_observed",
			"tls_writev_multi_iovec_observed",
			"io_uring_setup_observed",
			"tcp_state_ringbuf_reserve_failures",
		}
		for _, name := range names {
			ms, ok := spec.Maps[name]
			if !ok {
				t.Errorf("map %s not found in CollectionSpec", name)
				continue
			}
			if ms.Type != ebpf.PerCPUArray {
				t.Errorf("%s type = %v, want ebpf.PerCPUArray", name, ms.Type)
			}
			if ms.MaxEntries != 1 || ms.KeySize != 4 || ms.ValueSize != 4 {
				t.Errorf("%s unexpected shape MaxEntries=%d KeySize=%d ValueSize=%d",
					name, ms.MaxEntries, ms.KeySize, ms.ValueSize)
			}
		}
	})

	t.Run("partial_egress_observed is a 4-slot PERCPU_ARRAY (BG-01)", func(t *testing.T) {
		ms, ok := spec.Maps["partial_egress_observed"]
		if !ok {
			t.Fatal("map partial_egress_observed not found in CollectionSpec")
		}
		if ms.Type != ebpf.PerCPUArray {
			t.Errorf("partial_egress_observed type = %v, want ebpf.PerCPUArray", ms.Type)
		}
		if ms.MaxEntries != 4 {
			t.Errorf("partial_egress_observed MaxEntries = %d, want 4", ms.MaxEntries)
		}
		if ms.KeySize != 4 {
			t.Errorf("partial_egress_observed KeySize = %d, want 4", ms.KeySize)
		}
		if ms.ValueSize != 4 {
			t.Errorf("partial_egress_observed ValueSize = %d, want 4", ms.ValueSize)
		}
	})
}
