// Code in this package is generated by bpf2go. abi_test.go is hand-written
// and asserts the BPF↔Go capacity contract: the embedded ELF's
// `MaxEntries` for each defend-mode map (cgroup section + LSM section) must
// match the Go-side `policy.*` constants that callers use to gate inserts.
// Drift here equals silent BPF EINVAL on Update, surfacing as defend-bypass
// in production.
//
// Ports tests previously split across internal/bpf/tracedefend/abi_test.go
// and internal/bpf/tracelsmdefend/abi_test.go (collapsed into one package
// in SIMPLIFICATION_PLAN.md Phase 2.3).
//
// Pure spec parse via cilium/ebpf — no kernel needed; runs on any OS/arch
// covered by the generated _bpfel.go build constraints.

package defend

import (
	"testing"

	"github.com/cilium/ebpf"
	"github.com/coldstep-io/coldstep/internal/policy"
)

func TestDefendMapMaxEntriesMatchGoConstants(t *testing.T) {
	spec, err := LoadDefend()
	if err != nil {
		t.Fatalf("LoadDefend: %v", err)
	}

	cases := []struct {
		mapName        string
		expected       uint32
		goConstantName string
	}{
		{"allowed_ipv4", uint32(policy.MaxAllowedDefendIPv4Keys), "policy.MaxAllowedDefendIPv4Keys"},
		{"ignored_ipv4_lpm", uint32(policy.MaxIgnoredIPv4Nets), "policy.MaxIgnoredIPv4Nets"},
		{"lsm_allowed_ipv4", uint32(policy.MaxAllowedDefendIPv4Keys), "policy.MaxAllowedDefendIPv4Keys"},
		{"lsm_ignored_ipv4_lpm", uint32(policy.MaxIgnoredIPv4Nets), "policy.MaxIgnoredIPv4Nets"},
	}

	for _, c := range cases {
		ms, ok := spec.Maps[c.mapName]
		if !ok {
			t.Errorf("BPF map %q not found in CollectionSpec", c.mapName)
			continue
		}
		if ms.MaxEntries != c.expected {
			t.Errorf("BPF map %q MaxEntries = %d, want %d (Go constant %s)",
				c.mapName, ms.MaxEntries, c.expected, c.goConstantName)
		}
	}
}

func TestDenyReserveFailuresMapsArePerCPUArray(t *testing.T) {
	spec, err := LoadDefend()
	if err != nil {
		t.Fatalf("LoadDefend: %v", err)
	}
	for _, name := range []string{"deny_reserve_failures", "lsm_deny_reserve_failures"} {
		ms, ok := spec.Maps[name]
		if !ok {
			t.Fatalf("BPF map %q missing from CollectionSpec", name)
		}
		if ms.Type != ebpf.PerCPUArray {
			t.Fatalf("%s type = %v, want ebpf.PerCPUArray", name, ms.Type)
		}
		if ms.MaxEntries != 1 || ms.KeySize != 4 || ms.ValueSize != 4 {
			t.Fatalf("%s shape MaxEntries=%d KeySize=%d ValueSize=%d",
				name, ms.MaxEntries, ms.KeySize, ms.ValueSize)
		}
	}
}

// TestIPv6ObserveMapsArePerCPUArray asserts the P0-1 Phase 1 observe-only
// counter maps (ipv6_connect_observed, ipv6_sendmsg_observed) have the
// PERCPU_ARRAY shape userspace expects to sum. Maps are added in
// bpf/trace_defend_cgroup.inc; the test skips itself until the defend
// stubs have been regenerated on Linux to include them.
// TODO: remove skip after Linux regeneration of internal/bpf/defend/*_bpfel.go.
func TestIPv6ObserveMapsArePerCPUArray(t *testing.T) {
	spec, err := LoadDefend()
	if err != nil {
		t.Fatalf("LoadDefend: %v", err)
	}
	for _, name := range []string{"ipv6_connect_observed", "ipv6_sendmsg_observed"} {
		ms, ok := spec.Maps[name]
		if !ok {
			t.Skipf("defend stubs not regenerated yet: map %q absent from CollectionSpec — run `go generate ./internal/bpf/defend/` on Linux", name)
		}
		if ms.Type != ebpf.PerCPUArray {
			t.Errorf("%s type = %v, want ebpf.PerCPUArray", name, ms.Type)
		}
		if ms.MaxEntries != 1 || ms.KeySize != 4 || ms.ValueSize != 4 {
			t.Errorf("%s shape MaxEntries=%d KeySize=%d ValueSize=%d, want MaxEntries=1 KeySize=4 ValueSize=4",
				name, ms.MaxEntries, ms.KeySize, ms.ValueSize)
		}
	}
}

// TestIPv6ObservePrograms asserts the cgroup/connect6 + cgroup/sendmsg6
// programs are present in the spec with the CGroupSockAddr program type.
// Skips until the stubs are regenerated on Linux.
// TODO: remove skip after Linux regeneration.
func TestIPv6ObservePrograms(t *testing.T) {
	spec, err := LoadDefend()
	if err != nil {
		t.Fatalf("LoadDefend: %v", err)
	}
	for _, name := range []string{"defend_cgroup_connect6", "defend_cgroup_sendmsg6"} {
		ps, ok := spec.Programs[name]
		if !ok {
			t.Skipf("defend stubs not regenerated yet: program %q absent from CollectionSpec — run `go generate ./internal/bpf/defend/` on Linux", name)
		}
		if ps.Type != ebpf.CGroupSockAddr {
			t.Errorf("%s type = %v, want ebpf.CGroupSockAddr", name, ps.Type)
		}
	}
}

// TestSendpageObserveMapIsPerCPUArray asserts the sendpage_observed counter
// map (kernel-5.15 sendfile/splice gap) has the PERCPU_ARRAY shape userspace
// expects to sum. Added in bpf/trace_lsm_defend_lsm.inc; the test skips
// itself until the defend stubs have been regenerated on Linux to include it.
// TODO: remove skip after Linux regeneration of internal/bpf/defend/*_bpfel.go.
func TestSendpageObserveMapIsPerCPUArray(t *testing.T) {
	spec, err := LoadDefend()
	if err != nil {
		t.Fatalf("LoadDefend: %v", err)
	}
	ms, ok := spec.Maps["sendpage_observed"]
	if !ok {
		t.Skipf("defend stubs not regenerated yet: map \"sendpage_observed\" absent from CollectionSpec — run `go generate ./internal/bpf/defend/` on Linux")
	}
	if ms.Type != ebpf.PerCPUArray {
		t.Errorf("sendpage_observed type = %v, want ebpf.PerCPUArray", ms.Type)
	}
	if ms.MaxEntries != 1 || ms.KeySize != 4 || ms.ValueSize != 4 {
		t.Errorf("sendpage_observed shape MaxEntries=%d KeySize=%d ValueSize=%d, want MaxEntries=1 KeySize=4 ValueSize=4",
			ms.MaxEntries, ms.KeySize, ms.ValueSize)
	}
}

// TestSendpageHookProgram asserts the lsm/socket_sendpage program is
// present in the spec with the LSM program type. Skips until stubs are
// regenerated on Linux.
// TODO: remove skip after Linux regeneration.
func TestSendpageHookProgram(t *testing.T) {
	spec, err := LoadDefend()
	if err != nil {
		t.Fatalf("LoadDefend: %v", err)
	}
	ps, ok := spec.Programs["lsm_socket_sendpage"]
	if !ok {
		t.Skipf("defend stubs not regenerated yet: program \"lsm_socket_sendpage\" absent from CollectionSpec — run `go generate ./internal/bpf/defend/` on Linux")
	}
	if ps.Type != ebpf.LSM {
		t.Errorf("lsm_socket_sendpage type = %v, want ebpf.LSM", ps.Type)
	}
}
